image: gitlab/dind

services:
  - name: docker:dind

variables:
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: "/certs"
  WIZ_IAC_POLICY: "nixlab-iac-audit"
  WIZ_SECRETS_POLICY: "nixlab-secrets"
  WIZ_VULN_POLICY: "nixlab-vuln-audit"

default:
  before_script:
    - curl --silent -o wizcli https://wizcli.app.wiz.io/latest/wizcli-linux-amd64 && chmod +x wizcli
    - ./wizcli auth --id "$WIZ_CLIENT_ID" --secret "$WIZ_CLIENT_SECRET"

stages:
  - security
  - image-build-scan-push-tag

security-iac:
  stage: security
  variables:
    SCAN_PATH: "."
    POLICY: "Default IaC policy"
  script:
    - ./wizcli iac scan --path "$SCAN_PATH" -p "$WIZ_IAC_POLICY" -p "$WIZ_SECRETS_POLICY"

security-dir:
  stage: security
  variables:
    SCAN_PATH: "."
    POLICY: "Default secrets policy"
  script:
    - ./wizcli dir scan --path "$SCAN_PATH" -p "$WIZ_VULN_POLICY" -p "$WIZ_SECRETS_POLICY"

image-build-scan-push-tag:
  stage: image-build-scan-push-tag
  script:
    - docker build . --tag $CONTAINER_RELEASE_IMAGE
    - ./wizcli docker scan --image $CONTAINER_RELEASE_IMAGE -p "$WIZ_VULN_POLICY" -p "$WIZ_SECRETS_POLICY" --policy-hits-only --dockerfile "./Dockerfile" --output wiz-output.json,sarif,true
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CONTAINER_RELEASE_IMAGE
    - ./wizcli docker tag -S -i $CONTAINER_RELEASE_IMAGE
  artifacts:
    paths:
      - wiz-output.json
